#!/usr/bin/env python3
"""
Comprehensive university list - Top universities globally
Including: US (250), Canada (100), UK (100), Europe (100), India (100), Australia (50), Global (100)
"""

# Top 250 US Universities
US_UNIVERSITIES = {
    # Ivy League
    "Harvard University": "harvard.edu",
    "Yale University": "yale.edu",
    "Princeton University": "princeton.edu",
    "Columbia University": "columbia.edu",
    "University of Pennsylvania": "upenn.edu",
    "Brown University": "brown.edu",
    "Cornell University": "cornell.edu",
    "Dartmouth College": "dartmouth.edu",
    
    # Top Research Universities
    "Massachusetts Institute of Technology": "mit.edu",
    "Stanford University": "stanford.edu",
    "California Institute of Technology": "caltech.edu",
    "University of Chicago": "uchicago.edu",
    "Duke University": "duke.edu",
    "Johns Hopkins University": "jhu.edu",
    "Northwestern University": "northwestern.edu",
    "Vanderbilt University": "vanderbilt.edu",
    "Rice University": "rice.edu",
    "Washington University in St. Louis": "wustl.edu",
    "University of Notre Dame": "nd.edu",
    "Georgetown University": "georgetown.edu",
    "Emory University": "emory.edu",
    "University of California Berkeley": "berkeley.edu",
    "University of California Los Angeles": "ucla.edu",
    "University of Southern California": "usc.edu",
    "Carnegie Mellon University": "cmu.edu",
    "University of Virginia": "virginia.edu",
    "University of Michigan": "umich.edu",
    "New York University": "nyu.edu",
    "University of North Carolina Chapel Hill": "unc.edu",
    "Boston College": "bc.edu",
    "Boston University": "bu.edu",
    "Tufts University": "tufts.edu",
    "University of Rochester": "rochester.edu",
    "Case Western Reserve University": "case.edu",
    "University of California San Diego": "ucsd.edu",
    "Georgia Institute of Technology": "gatech.edu",
    "University of Florida": "ufl.edu",
    "University of Texas Austin": "utexas.edu",
    "University of Illinois Urbana-Champaign": "illinois.edu",
    "University of Wisconsin Madison": "wisc.edu",
    "Ohio State University": "osu.edu",
    "Pennsylvania State University": "psu.edu",
    "University of Washington": "washington.edu",
    "University of Minnesota": "umn.edu",
    "Indiana University": "indiana.edu",
    "Michigan State University": "msu.edu",
    "University of Maryland": "umd.edu",
    "University of Pittsburgh": "pitt.edu",
    "University of California Davis": "ucdavis.edu",
    "University of California Irvine": "uci.edu",
    "University of California Santa Barbara": "ucsb.edu",
    "University of Colorado Boulder": "colorado.edu",
    "University of Arizona": "arizona.edu",
    "Arizona State University": "asu.edu",
    "University of Utah": "utah.edu",
    "University of Oregon": "uoregon.edu",
    "University of Iowa": "uiowa.edu",
    "Iowa State University": "iastate.edu",
    "University of Georgia": "uga.edu",
    "University of Tennessee": "utk.edu",
    "University of Kentucky": "uky.edu",
    "University of Alabama": "ua.edu",
    "Auburn University": "auburn.edu",
    "Louisiana State University": "lsu.edu",
    "University of Missouri": "missouri.edu",
    "University of Nebraska": "unl.edu",
    "University of Kansas": "ku.edu",
    "University of Oklahoma": "ou.edu",
    "Texas A&M University": "tamu.edu",
    "University of Miami": "miami.edu",
    "Florida State University": "fsu.edu",
    "Clemson University": "clemson.edu",
    "Virginia Tech": "vt.edu",
    "North Carolina State University": "ncsu.edu",
    "University of South Carolina": "sc.edu",
    "University of Connecticut": "uconn.edu",
    "University of Massachusetts Amherst": "umass.edu",
    "Northeastern University": "northeastern.edu",
    "George Washington University": "gwu.edu",
    "American University": "american.edu",
    "Syracuse University": "syr.edu",
    "University of Delaware": "udel.edu",
    "Rutgers University": "rutgers.edu",
    "Temple University": "temple.edu",
    "Drexel University": "drexel.edu",
    "University of Vermont": "uvm.edu",
    "University of New Hampshire": "unh.edu",
    "University of Maine": "maine.edu",
    "University of Rhode Island": "uri.edu",
    
    # Liberal Arts Colleges
    "Williams College": "williams.edu",
    "Amherst College": "amherst.edu",
    "Swarthmore College": "swarthmore.edu",
    "Wellesley College": "wellesley.edu",
    "Bowdoin College": "bowdoin.edu",
    "Middlebury College": "middlebury.edu",
    "Pomona College": "pomona.edu",
    "Carleton College": "carleton.edu",
    "Claremont McKenna College": "cmc.edu",
    "Davidson College": "davidson.edu",
    "Haverford College": "haverford.edu",
    "Vassar College": "vassar.edu",
    "Colby College": "colby.edu",
    "Hamilton College": "hamilton.edu",
    "Wesleyan University": "wesleyan.edu",
    "Bates College": "bates.edu",
    "Grinnell College": "grinnell.edu",
    "Smith College": "smith.edu",
    "Mount Holyoke College": "mtholyoke.edu",
    "Bryn Mawr College": "brynmawr.edu",
    "Barnard College": "barnard.edu",
    "Oberlin College": "oberlin.edu",
    "Macalester College": "macalester.edu",
    "Reed College": "reed.edu",
    "Kenyon College": "kenyon.edu",
    "Colorado College": "coloradocollege.edu",
    "Bucknell University": "bucknell.edu",
    "Colgate University": "colgate.edu",
    "Lafayette College": "lafayette.edu",
    "Trinity College": "trincoll.edu",
    "Connecticut College": "conncoll.edu",
    "Union College": "union.edu",
    "Skidmore College": "skidmore.edu",
    "Whitman College": "whitman.edu",
    "Occidental College": "oxy.edu",
    "Franklin and Marshall College": "fandm.edu",
    "Dickinson College": "dickinson.edu",
    "Gettysburg College": "gettysburg.edu",
    "DePauw University": "depauw.edu",
    "Denison University": "denison.edu",
    "Wabash College": "wabash.edu",
    "Centre College": "centre.edu",
    "Rhodes College": "rhodes.edu",
    "Sewanee": "sewanee.edu",
    "Furman University": "furman.edu",
    "Trinity University": "trinity.edu",
    "St. Olaf College": "stolaf.edu",
    "Lawrence University": "lawrence.edu",
    
    # Additional Top Universities
    "Tulane University": "tulane.edu",
    "University of Richmond": "richmond.edu",
    "Wake Forest University": "wfu.edu",
    "Lehigh University": "lehigh.edu",
    "Villanova University": "villanova.edu",
    "University of San Diego": "sandiego.edu",
    "Loyola Marymount University": "lmu.edu",
    "Santa Clara University": "scu.edu",
    "Gonzaga University": "gonzaga.edu",
    "Marquette University": "marquette.edu",
    "Creighton University": "creighton.edu",
    "Xavier University": "xavier.edu",
    "University of Dayton": "udayton.edu",
    "Saint Louis University": "slu.edu",
    "DePaul University": "depaul.edu",
    "Loyola University Chicago": "luc.edu",
    "University of San Francisco": "usfca.edu",
    "Seattle University": "seattleu.edu",
    "University of Portland": "up.edu",
    "University of Denver": "du.edu",
    "University of Tulsa": "utulsa.edu",
    "Southern Methodist University": "smu.edu",
    "Texas Christian University": "tcu.edu",
    "Baylor University": "baylor.edu",
    "Pepperdine University": "pepperdine.edu",
    "Chapman University": "chapman.edu",
    "University of the Pacific": "pacific.edu",
    "Hofstra University": "hofstra.edu",
    "Fordham University": "fordham.edu",
    "St. John's University": "stjohns.edu",
    "Pace University": "pace.edu",
    "Adelphi University": "adelphi.edu",
    "Rochester Institute of Technology": "rit.edu",
    "Rensselaer Polytechnic Institute": "rpi.edu",
    "Worcester Polytechnic Institute": "wpi.edu",
    "Stevens Institute of Technology": "stevens.edu",
    "Illinois Institute of Technology": "iit.edu",
    "Colorado School of Mines": "mines.edu",
    "Missouri University of Science and Technology": "mst.edu",
    "New Jersey Institute of Technology": "njit.edu",
    "Clarkson University": "clarkson.edu",
    "University of Alabama Birmingham": "uab.edu",
    "University of Cincinnati": "uc.edu",
    "University of Houston": "uh.edu",
    "University of Nevada Las Vegas": "unlv.edu",
    "University of New Mexico": "unm.edu",
    "University of Wyoming": "uwyo.edu",
    "University of Montana": "umt.edu",
    "University of Idaho": "uidaho.edu",
    "University of North Dakota": "und.edu",
    "University of South Dakota": "usd.edu",
    "University of Arkansas": "uark.edu",
    "University of Mississippi": "olemiss.edu",
    "West Virginia University": "wvu.edu",
    "University of Hawaii": "hawaii.edu",
    "University of Alaska": "alaska.edu",
    
    # State Universities
    "San Diego State University": "sdsu.edu",
    "California State University Long Beach": "csulb.edu",
    "San Jose State University": "sjsu.edu",
    "California State University Fullerton": "fullerton.edu",
    "California Polytechnic State University": "calpoly.edu",
    "University of Central Florida": "ucf.edu",
    "Florida International University": "fiu.edu",
    "University of South Florida": "usf.edu",
    "Georgia State University": "gsu.edu",
    "Kennesaw State University": "kennesaw.edu",
    "University of North Texas": "unt.edu",
    "University of Texas Dallas": "utdallas.edu",
    "University of Texas San Antonio": "utsa.edu",
    "Texas Tech University": "ttu.edu",
    "University of Nevada Reno": "unr.edu",
    "Portland State University": "pdx.edu",
    "Washington State University": "wsu.edu",
    "Oregon State University": "oregonstate.edu",
    "Colorado State University": "colostate.edu",
    "Utah State University": "usu.edu",
    "New Mexico State University": "nmsu.edu",
    "Montana State University": "montana.edu",
    "Boise State University": "boisestate.edu",
    "University of Louisville": "louisville.edu",
    "University of Memphis": "memphis.edu",
    "University of New Orleans": "uno.edu",
    "Old Dominion University": "odu.edu",
    "George Mason University": "gmu.edu",
    "James Madison University": "jmu.edu",
    "Towson University": "towson.edu",
    "University of Maryland Baltimore County": "umbc.edu",
    "Virginia Commonwealth University": "vcu.edu",
    "University of North Carolina Charlotte": "uncc.edu",
    "University of North Carolina Greensboro": "uncg.edu",
    "East Carolina University": "ecu.edu",
    "Western Michigan University": "wmich.edu",
    "Central Michigan University": "cmich.edu",
    "Eastern Michigan University": "emich.edu",
    "Oakland University": "oakland.edu",
    "Wayne State University": "wayne.edu",
    "University of Wisconsin Milwaukee": "uwm.edu",
    "University of Illinois Chicago": "uic.edu",
    "Northern Illinois University": "niu.edu",
    "Southern Illinois University": "siu.edu",
    "Ball State University": "bsu.edu",
    "University of Toledo": "utoledo.edu",
    "Kent State University": "kent.edu",
    "University of Akron": "uakron.edu",
    "Wright State University": "wright.edu",
    "Cleveland State University": "csuohio.edu",
    "University of Missouri Kansas City": "umkc.edu",
    "University of Missouri St. Louis": "umsl.edu",
    "Saint Joseph's University": "sju.edu",
    "La Salle University": "lasalle.edu",
    "Duquesne University": "duq.edu",
    "University of Scranton": "scranton.edu",
    "Seton Hall University": "shu.edu",
    "Fairfield University": "fairfield.edu",
    "Providence College": "providence.edu",
    "College of the Holy Cross": "holycross.edu",
    "Stonehill College": "stonehill.edu",
    "Assumption University": "assumption.edu",
    "Bentley University": "bentley.edu",
    "Bryant University": "bryant.edu",
    "Babson College": "babson.edu",
    "Olin College": "olin.edu",
    "Clark University": "clarku.edu",
    "Brandeis University": "brandeis.edu"
}

# Top 100 Canadian Universities
CANADIAN_UNIVERSITIES = {
    "University of Toronto": "utoronto.ca",
    "University of British Columbia": "ubc.ca",
    "McGill University": "mcgill.ca",
    "McMaster University": "mcmaster.ca",
    "University of Alberta": "ualberta.ca",
    "University of Montreal": "umontreal.ca",
    "University of Calgary": "ucalgary.ca",
    "University of Ottawa": "uottawa.ca",
    "University of Waterloo": "uwaterloo.ca",
    "Western University": "uwo.ca",
    "Queen's University": "queensu.ca",
    "University of Manitoba": "umanitoba.ca",
    "Dalhousie University": "dal.ca",
    "Laval University": "ulaval.ca",
    "University of Saskatchewan": "usask.ca",
    "Simon Fraser University": "sfu.ca",
    "University of Victoria": "uvic.ca",
    "York University": "yorku.ca",
    "Carleton University": "carleton.ca",
    "University of Guelph": "uoguelph.ca",
    "Memorial University": "mun.ca",
    "Ryerson University": "ryerson.ca",
    "Concordia University": "concordia.ca",
    "University of Regina": "uregina.ca",
    "University of Windsor": "uwindsor.ca",
    "University of New Brunswick": "unb.ca",
    "Brock University": "brocku.ca",
    "Wilfrid Laurier University": "wlu.ca",
    "University of Lethbridge": "uleth.ca",
    "UQAM": "uqam.ca",
    "Sherbrooke University": "usherbrooke.ca",
    "University of Winnipeg": "uwinnipeg.ca",
    "Trent University": "trentu.ca",
    "University of Northern British Columbia": "unbc.ca",
    "Acadia University": "acadiau.ca",
    "Saint Mary's University": "smu.ca",
    "Mount Allison University": "mta.ca",
    "St. Francis Xavier University": "stfx.ca",
    "Bishop's University": "ubishops.ca",
    "Brandon University": "brandonu.ca",
    "Mount Royal University": "mtroyal.ca",
    "MacEwan University": "macewan.ca",
    "Vancouver Island University": "viu.ca",
    "Kwantlen Polytechnic University": "kpu.ca",
    "Thompson Rivers University": "tru.ca",
    "University of the Fraser Valley": "ufv.ca",
    "Capilano University": "capilanou.ca",
    "Emily Carr University": "ecuad.ca",
    "OCAD University": "ocadu.ca",
    "Nipissing University": "nipissingu.ca",
    "Laurentian University": "laurentian.ca",
    "Lakehead University": "lakeheadu.ca",
    "UOIT": "ontariotechu.ca",
    "Algoma University": "algomau.ca",
    "Royal Roads University": "royalroads.ca",
    "Trinity Western University": "twu.ca",
    "University of Prince Edward Island": "upei.ca",
    "Cape Breton University": "cbu.ca",
    "Mount Saint Vincent University": "msvu.ca",
    "NSCAD University": "nscad.ca",
    "Université de Moncton": "umoncton.ca",
    "HEC Montreal": "hec.ca",
    "Polytechnique Montreal": "polymtl.ca",
    "ETS Montreal": "etsmtl.ca",
    "ENAP": "enap.ca",
    "TELUQ": "teluq.ca",
    "Université du Québec à Chicoutimi": "uqac.ca",
    "Université du Québec à Rimouski": "uqar.ca",
    "Université du Québec à Trois-Rivières": "uqtr.ca",
    "Université du Québec en Outaouais": "uqo.ca",
    "Université du Québec en Abitibi-Témiscamingue": "uqat.ca",
    "Royal Military College": "rmc-cmr.ca",
    "Dominican University College": "udominicaine.ca",
    "Canadian Mennonite University": "cmu.ca",
    "First Nations University": "fnuniv.ca",
    "St. Thomas University": "stu.ca",
    "Crandall University": "crandallu.ca",
    "Kingswood University": "kingswood.edu",
    "Yorkville University": "yorkvilleu.ca",
    "University Canada West": "ucanwest.ca",
    "Quest University": "questu.ca",
    "Fairleigh Dickinson University Vancouver": "fdu.edu",
    "New York Institute of Technology Vancouver": "nyit.edu",
    "Northeastern University Vancouver": "northeastern.edu",
    "SAIT": "sait.ca",
    "NAIT": "nait.ca",
    "BCIT": "bcit.ca",
    "Conestoga College": "conestogac.on.ca",
    "George Brown College": "georgebrown.ca",
    "Seneca College": "senecacollege.ca",
    "Humber College": "humber.ca",
    "Centennial College": "centennialcollege.ca",
    "Sheridan College": "sheridancollege.ca",
    "Algonquin College": "algonquincollege.com",
    "Fanshawe College": "fanshawec.ca",
    "Mohawk College": "mohawkcollege.ca",
    "Durham College": "durhamcollege.ca",
    "Fleming College": "flemingcollege.ca",
    "Cambrian College": "cambriancollege.ca",
    "Canadore College": "canadorecollege.ca",
    "Confederation College": "confederationcollege.ca",
    "Sault College": "saultcollege.ca",
    "Niagara College": "niagaracollege.ca"
}

# Top 100 UK Universities
UK_UNIVERSITIES = {
    "University of Oxford": "ox.ac.uk",
    "University of Cambridge": "cam.ac.uk",
    "Imperial College London": "imperial.ac.uk",
    "London School of Economics": "lse.ac.uk",
    "University College London": "ucl.ac.uk",
    "University of Edinburgh": "ed.ac.uk",
    "King's College London": "kcl.ac.uk",
    "University of Manchester": "manchester.ac.uk",
    "University of Bristol": "bristol.ac.uk",
    "University of Warwick": "warwick.ac.uk",
    "University of Glasgow": "gla.ac.uk",
    "University of Sheffield": "sheffield.ac.uk",
    "Durham University": "dur.ac.uk",
    "University of Birmingham": "bham.ac.uk",
    "University of Leeds": "leeds.ac.uk",
    "University of Nottingham": "nottingham.ac.uk",
    "University of Southampton": "soton.ac.uk",
    "University of St Andrews": "st-andrews.ac.uk",
    "Queen Mary University": "qmul.ac.uk",
    "University of York": "york.ac.uk",
    "Lancaster University": "lancaster.ac.uk",
    "University of Exeter": "exeter.ac.uk",
    "Newcastle University": "ncl.ac.uk",
    "University of Liverpool": "liverpool.ac.uk",
    "University of Aberdeen": "abdn.ac.uk",
    "University of Bath": "bath.ac.uk",
    "University of Reading": "reading.ac.uk",
    "Cardiff University": "cardiff.ac.uk",
    "Queen's University Belfast": "qub.ac.uk",
    "University of Dundee": "dundee.ac.uk",
    "University of East Anglia": "uea.ac.uk",
    "University of Leicester": "le.ac.uk",
    "University of Surrey": "surrey.ac.uk",
    "University of Strathclyde": "strath.ac.uk",
    "Heriot-Watt University": "hw.ac.uk",
    "Royal Holloway": "rhul.ac.uk",
    "University of Sussex": "sussex.ac.uk",
    "University of Kent": "kent.ac.uk",
    "Loughborough University": "lboro.ac.uk",
    "SOAS University": "soas.ac.uk",
    "University of Essex": "essex.ac.uk",
    "Swansea University": "swansea.ac.uk",
    "Aberystwyth University": "aber.ac.uk",
    "Bangor University": "bangor.ac.uk",
    "Brunel University": "brunel.ac.uk",
    "City University": "city.ac.uk",
    "Aston University": "aston.ac.uk",
    "University of Hull": "hull.ac.uk",
    "Oxford Brookes University": "brookes.ac.uk",
    "University of Plymouth": "plymouth.ac.uk",
    "University of Portsmouth": "port.ac.uk",
    "University of Stirling": "stir.ac.uk",
    "Northumbria University": "northumbria.ac.uk",
    "Keele University": "keele.ac.uk",
    "Coventry University": "coventry.ac.uk",
    "Ulster University": "ulster.ac.uk",
    "University of Bradford": "bradford.ac.uk",
    "De Montfort University": "dmu.ac.uk",
    "Edinburgh Napier University": "napier.ac.uk",
    "Glasgow Caledonian University": "gcu.ac.uk",
    "Robert Gordon University": "rgu.ac.uk",
    "University of Greenwich": "gre.ac.uk",
    "University of Hertfordshire": "herts.ac.uk",
    "University of Huddersfield": "hud.ac.uk",
    "Kingston University": "kingston.ac.uk",
    "University of Lincoln": "lincoln.ac.uk",
    "Liverpool John Moores University": "ljmu.ac.uk",
    "Manchester Metropolitan University": "mmu.ac.uk",
    "Middlesex University": "mdx.ac.uk",
    "Nottingham Trent University": "ntu.ac.uk",
    "University of Salford": "salford.ac.uk",
    "Sheffield Hallam University": "shu.ac.uk",
    "University of Brighton": "brighton.ac.uk",
    "University of Central Lancashire": "uclan.ac.uk",
    "University of East London": "uel.ac.uk",
    "University of West London": "uwl.ac.uk",
    "University of Westminster": "westminster.ac.uk",
    "Birmingham City University": "bcu.ac.uk",
    "University of Derby": "derby.ac.uk",
    "University of Gloucestershire": "glos.ac.uk",
    "Leeds Beckett University": "leedsbeckett.ac.uk",
    "London Metropolitan University": "londonmet.ac.uk",
    "University of Northampton": "northampton.ac.uk",
    "University of Roehampton": "roehampton.ac.uk",
    "University of South Wales": "southwales.ac.uk",
    "Staffordshire University": "staffs.ac.uk",
    "Teesside University": "tees.ac.uk",
    "University of West of England": "uwe.ac.uk",
    "University of Wolverhampton": "wlv.ac.uk",
    "Anglia Ruskin University": "aru.ac.uk",
    "Bath Spa University": "bathspa.ac.uk",
    "Canterbury Christ Church University": "canterbury.ac.uk",
    "Edge Hill University": "edgehill.ac.uk",
    "University of Chester": "chester.ac.uk",
    "University of Chichester": "chi.ac.uk",
    "Falmouth University": "falmouth.ac.uk",
    "University of Winchester": "winchester.ac.uk",
    "York St John University": "yorksj.ac.uk",
    "Bournemouth University": "bournemouth.ac.uk",
    "University of Bedfordshire": "beds.ac.uk",
    "University of Bolton": "bolton.ac.uk",
    "University of Cumbria": "cumbria.ac.uk",
    "University of Sunderland": "sunderland.ac.uk"
}

# Top 100 European Universities (excluding UK)
EUROPEAN_UNIVERSITIES = {
    # Switzerland
    "ETH Zurich": "ethz.ch",
    "EPFL": "epfl.ch",
    "University of Zurich": "uzh.ch",
    "University of Geneva": "unige.ch",
    "University of Basel": "unibas.ch",
    "University of Bern": "unibe.ch",
    "University of Lausanne": "unil.ch",
    "University of St. Gallen": "unisg.ch",
    
    # Germany
    "Technical University of Munich": "tum.de",
    "Ludwig Maximilian University": "lmu.de",
    "Heidelberg University": "uni-heidelberg.de",
    "Humboldt University Berlin": "hu-berlin.de",
    "Free University Berlin": "fu-berlin.de",
    "Technical University Berlin": "tu-berlin.de",
    "RWTH Aachen": "rwth-aachen.de",
    "University of Freiburg": "uni-freiburg.de",
    "University of Tübingen": "uni-tuebingen.de",
    "University of Göttingen": "uni-goettingen.de",
    "University of Hamburg": "uni-hamburg.de",
    "University of Bonn": "uni-bonn.de",
    "University of Mannheim": "uni-mannheim.de",
    "University of Cologne": "uni-koeln.de",
    "University of Frankfurt": "uni-frankfurt.de",
    "University of Stuttgart": "uni-stuttgart.de",
    "Karlsruhe Institute of Technology": "kit.edu",
    
    # France
    "Sorbonne University": "sorbonne-universite.fr",
    "École Normale Supérieure": "ens.fr",
    "École Polytechnique": "polytechnique.edu",
    "Sciences Po": "sciencespo.fr",
    "HEC Paris": "hec.edu",
    "INSEAD": "insead.edu",
    "Paris-Saclay University": "universite-paris-saclay.fr",
    "PSL University": "psl.eu",
    "Institut Polytechnique de Paris": "ip-paris.fr",
    "Université de Paris": "u-paris.fr",
    "Université Grenoble Alpes": "univ-grenoble-alpes.fr",
    "Aix-Marseille University": "univ-amu.fr",
    "University of Lyon": "universite-lyon.fr",
    "University of Toulouse": "univ-toulouse.fr",
    "University of Bordeaux": "u-bordeaux.fr",
    "University of Strasbourg": "unistra.fr",
    
    # Netherlands
    "University of Amsterdam": "uva.nl",
    "Delft University of Technology": "tudelft.nl",
    "Utrecht University": "uu.nl",
    "Leiden University": "leidenuniv.nl",
    "Erasmus University Rotterdam": "eur.nl",
    "University of Groningen": "rug.nl",
    "Wageningen University": "wur.nl",
    "Eindhoven University of Technology": "tue.nl",
    "Radboud University": "ru.nl",
    "Maastricht University": "maastrichtuniversity.nl",
    "VU Amsterdam": "vu.nl",
    "Tilburg University": "tilburguniversity.edu",
    
    # Belgium
    "KU Leuven": "kuleuven.be",
    "Ghent University": "ugent.be",
    "Université Catholique de Louvain": "uclouvain.be",
    "Université Libre de Bruxelles": "ulb.be",
    "University of Antwerp": "uantwerpen.be",
    "Vrije Universiteit Brussel": "vub.be",
    
    # Sweden
    "Karolinska Institute": "ki.se",
    "Lund University": "lu.se",
    "Uppsala University": "uu.se",
    "Stockholm University": "su.se",
    "KTH Royal Institute": "kth.se",
    "Chalmers University": "chalmers.se",
    "University of Gothenburg": "gu.se",
    
    # Denmark
    "University of Copenhagen": "ku.dk",
    "Technical University of Denmark": "dtu.dk",
    "Aarhus University": "au.dk",
    "Copenhagen Business School": "cbs.dk",
    "Aalborg University": "aau.dk",
    
    # Norway
    "University of Oslo": "uio.no",
    "University of Bergen": "uib.no",
    "Norwegian University of Science and Technology": "ntnu.no",
    "University of Tromsø": "uit.no",
    
    # Finland
    "University of Helsinki": "helsinki.fi",
    "Aalto University": "aalto.fi",
    "University of Turku": "utu.fi",
    "University of Oulu": "oulu.fi",
    
    # Austria
    "University of Vienna": "univie.ac.at",
    "Vienna University of Technology": "tuwien.ac.at",
    "University of Innsbruck": "uibk.ac.at",
    "Medical University of Vienna": "meduniwien.ac.at",
    
    # Italy
    "University of Bologna": "unibo.it",
    "Sapienza University Rome": "uniroma1.it",
    "University of Milan": "unimi.it",
    "Politecnico di Milano": "polimi.it",
    "University of Padua": "unipd.it",
    "University of Pisa": "unipi.it",
    "University of Florence": "unifi.it",
    "University of Naples": "unina.it",
    "University of Turin": "unito.it",
    "Bocconi University": "unibocconi.it",
    
    # Spain
    "University of Barcelona": "ub.edu",
    "Autonomous University of Barcelona": "uab.cat",
    "Complutense University Madrid": "ucm.es",
    "Autonomous University of Madrid": "uam.es",
    "University of Valencia": "uv.es",
    "Pompeu Fabra University": "upf.edu",
    "IE University": "ie.edu",
    "IESE Business School": "iese.edu",
    "ESADE": "esade.edu",
    
    # Portugal
    "University of Porto": "up.pt",
    "University of Lisbon": "ulisboa.pt",
    "Nova University Lisbon": "unl.pt",
    "University of Coimbra": "uc.pt"
}

# Top 100 Indian Universities
INDIAN_UNIVERSITIES = {
    # IITs
    "IIT Bombay": "iitb.ac.in",
    "IIT Delhi": "iitd.ac.in",
    "IIT Madras": "iitm.ac.in",
    "IIT Kanpur": "iitk.ac.in",
    "IIT Kharagpur": "iitkgp.ac.in",
    "IIT Roorkee": "iitr.ac.in",
    "IIT Guwahati": "iitg.ac.in",
    "IIT Hyderabad": "iith.ac.in",
    "IIT Gandhinagar": "iitgn.ac.in",
    "IIT Ropar": "iitrpr.ac.in",
    "IIT Bhubaneswar": "iitbbs.ac.in",
    "IIT Mandi": "iitmandi.ac.in",
    "IIT Indore": "iiti.ac.in",
    "IIT Patna": "iitp.ac.in",
    "IIT Jodhpur": "iitj.ac.in",
    "IIT Tirupati": "iittp.ac.in",
    "IIT Palakkad": "iitpkd.ac.in",
    "IIT Jammu": "iitjammu.ac.in",
    "IIT Bhilai": "iitbhilai.ac.in",
    "IIT Goa": "iitgoa.ac.in",
    "IIT Dharwad": "iitdh.ac.in",
    "IIT ISM Dhanbad": "iitism.ac.in",
    "IIT BHU": "iitbhu.ac.in",
    
    # IIMs
    "IIM Ahmedabad": "iima.ac.in",
    "IIM Bangalore": "iimb.ac.in",
    "IIM Calcutta": "iimcal.ac.in",
    "IIM Lucknow": "iiml.ac.in",
    "IIM Kozhikode": "iimk.ac.in",
    "IIM Indore": "iimidr.ac.in",
    "IIM Shillong": "iimshillong.ac.in",
    "IIM Rohtak": "iimrohtak.ac.in",
    "IIM Ranchi": "iimranchi.ac.in",
    "IIM Raipur": "iimraipur.ac.in",
    "IIM Tiruchirappalli": "iimtrichy.ac.in",
    "IIM Udaipur": "iimu.ac.in",
    "IIM Kashipur": "iimkashipur.ac.in",
    "IIM Amritsar": "iimamritsar.ac.in",
    "IIM Bodhgaya": "iimbg.ac.in",
    "IIM Jammu": "iimj.ac.in",
    "IIM Nagpur": "iimnagpur.ac.in",
    "IIM Sambalpur": "iimsambalpur.ac.in",
    "IIM Sirmaur": "iimsirmaur.ac.in",
    "IIM Visakhapatnam": "iimv.ac.in",
    
    # NITs
    "NIT Trichy": "nitt.edu",
    "NIT Karnataka": "nitk.ac.in",
    "NIT Warangal": "nitw.ac.in",
    "NIT Calicut": "nitc.ac.in",
    "NIT Kurukshetra": "nitkkr.ac.in",
    "NIT Jaipur": "mnit.ac.in",
    "NIT Surat": "svnit.ac.in",
    "NIT Allahabad": "mnnit.ac.in",
    "NIT Bhopal": "manit.ac.in",
    "NIT Durgapur": "nitdgp.ac.in",
    
    # Central Universities
    "Jawaharlal Nehru University": "jnu.ac.in",
    "University of Delhi": "du.ac.in",
    "Banaras Hindu University": "bhu.ac.in",
    "Aligarh Muslim University": "amu.ac.in",
    "University of Hyderabad": "uohyd.ac.in",
    "Jamia Millia Islamia": "jmi.ac.in",
    "Pondicherry University": "pondiuni.edu.in",
    "Visva-Bharati University": "visvabharati.ac.in",
    "Tezpur University": "tezu.ernet.in",
    "North Eastern Hill University": "nehu.ac.in",
    
    # State Universities
    "University of Mumbai": "mu.ac.in",
    "University of Calcutta": "caluniv.ac.in",
    "University of Madras": "unom.ac.in",
    "Pune University": "unipune.ac.in",
    "Osmania University": "osmania.ac.in",
    "Anna University": "annauniv.edu",
    "Jadavpur University": "jadavpuruniversity.in",
    "University of Kerala": "keralauniversity.ac.in",
    "Andhra University": "andhrauniversity.edu.in",
    "University of Mysore": "uni-mysore.ac.in",
    
    # IISc and IISER
    "Indian Institute of Science": "iisc.ac.in",
    "IISER Pune": "iiserpune.ac.in",
    "IISER Kolkata": "iiserkol.ac.in",
    "IISER Mohali": "iisermohali.ac.in",
    "IISER Bhopal": "iiserb.ac.in",
    "IISER Thiruvananthapuram": "iisertvm.ac.in",
    
    # Medical Institutes
    "AIIMS Delhi": "aiims.edu",
    "Christian Medical College": "cmch-vellore.edu",
    "JIPMER": "jipmer.edu.in",
    "PGIMER": "pgimer.edu.in",
    
    # Private Universities
    "BITS Pilani": "bits-pilani.ac.in",
    "Manipal University": "manipal.edu",
    "VIT University": "vit.ac.in",
    "SRM University": "srmist.edu.in",
    "Amrita University": "amrita.edu",
    "Symbiosis International": "siu.edu.in",
    "Ashoka University": "ashoka.edu.in",
    "O.P. Jindal Global University": "jgu.edu.in",
    "Shiv Nadar University": "snu.edu.in",
    "NMIMS": "nmims.edu",
    "Christ University": "christuniversity.in",
    "Lovely Professional University": "lpu.in",
    "Bennett University": "bennett.edu.in",
    "Amity University": "amity.edu"
}

# Top 50 Australian Universities
AUSTRALIAN_UNIVERSITIES = {
    "University of Melbourne": "unimelb.edu.au",
    "Australian National University": "anu.edu.au",
    "University of Sydney": "sydney.edu.au",
    "University of Queensland": "uq.edu.au",
    "Monash University": "monash.edu",
    "University of New South Wales": "unsw.edu.au",
    "University of Western Australia": "uwa.edu.au",
    "University of Adelaide": "adelaide.edu.au",
    "University of Technology Sydney": "uts.edu.au",
    "University of Wollongong": "uow.edu.au",
    "University of Newcastle": "newcastle.edu.au",
    "Macquarie University": "mq.edu.au",
    "RMIT University": "rmit.edu.au",
    "Queensland University of Technology": "qut.edu.au",
    "Curtin University": "curtin.edu.au",
    "Deakin University": "deakin.edu.au",
    "University of South Australia": "unisa.edu.au",
    "Griffith University": "griffith.edu.au",
    "University of Tasmania": "utas.edu.au",
    "La Trobe University": "latrobe.edu.au",
    "Swinburne University": "swinburne.edu.au",
    "Bond University": "bond.edu.au",
    "Flinders University": "flinders.edu.au",
    "James Cook University": "jcu.edu.au",
    "Western Sydney University": "westernsydney.edu.au",
    "Murdoch University": "murdoch.edu.au",
    "Edith Cowan University": "ecu.edu.au",
    "Charles Darwin University": "cdu.edu.au",
    "University of Canberra": "canberra.edu.au",
    "Southern Cross University": "scu.edu.au",
    "Victoria University": "vu.edu.au",
    "Central Queensland University": "cqu.edu.au",
    "University of Southern Queensland": "usq.edu.au",
    "Charles Sturt University": "csu.edu.au",
    "University of New England": "une.edu.au",
    "Federation University": "federation.edu.au",
    "Australian Catholic University": "acu.edu.au",
    "University of the Sunshine Coast": "usc.edu.au",
    "University of Notre Dame Australia": "nd.edu.au",
    "University of Divinity": "divinity.edu.au",
    "Torrens University": "torrens.edu.au",
    "Carnegie Mellon Australia": "australia.cmu.edu",
    "University College London Australia": "ucl.ac.uk",
    "Monash University Malaysia": "monash.edu.my",
    "Curtin University Singapore": "curtin.edu.sg",
    "James Cook Singapore": "jcu.edu.sg",
    "University of Newcastle Singapore": "newcastle.edu.sg",
    "Murdoch University Dubai": "murdochuniversitydubai.com",
    "University of Wollongong Dubai": "uowdubai.ac.ae",
    "RMIT Vietnam": "rmit.edu.vn"
}

# Top 100 Global Universities (mix of best worldwide)
GLOBAL_TOP_UNIVERSITIES = {
    # Asia-Pacific
    "National University of Singapore": "nus.edu.sg",
    "Nanyang Technological University": "ntu.edu.sg",
    "University of Hong Kong": "hku.hk",
    "Chinese University of Hong Kong": "cuhk.edu.hk",
    "Hong Kong University of Science and Technology": "ust.hk",
    "University of Tokyo": "u-tokyo.ac.jp",
    "Kyoto University": "kyoto-u.ac.jp",
    "Tokyo Institute of Technology": "titech.ac.jp",
    "Osaka University": "osaka-u.ac.jp",
    "Tohoku University": "tohoku.ac.jp",
    "Nagoya University": "nagoya-u.ac.jp",
    "Kyushu University": "kyushu-u.ac.jp",
    "Hokkaido University": "hokudai.ac.jp",
    "Keio University": "keio.ac.jp",
    "Waseda University": "waseda.jp",
    "Seoul National University": "snu.ac.kr",
    "KAIST": "kaist.ac.kr",
    "Yonsei University": "yonsei.ac.kr",
    "Sungkyunkwan University": "skku.edu",
    "POSTECH": "postech.ac.kr",
    "Korea University": "korea.ac.kr",
    "Hanyang University": "hanyang.ac.kr",
    "Tsinghua University": "tsinghua.edu.cn",
    "Peking University": "pku.edu.cn",
    "Fudan University": "fudan.edu.cn",
    "Shanghai Jiao Tong University": "sjtu.edu.cn",
    "Zhejiang University": "zju.edu.cn",
    "University of Science and Technology of China": "ustc.edu.cn",
    "Nanjing University": "nju.edu.cn",
    "Wuhan University": "whu.edu.cn",
    "Harbin Institute of Technology": "hit.edu.cn",
    "Sun Yat-sen University": "sysu.edu.cn",
    "National Taiwan University": "ntu.edu.tw",
    "National Tsing Hua University": "nthu.edu.tw",
    "National Cheng Kung University": "ncku.edu.tw",
    
    # Middle East
    "King Abdulaziz University": "kau.edu.sa",
    "King Saud University": "ksu.edu.sa",
    "King Abdullah University": "kaust.edu.sa",
    "American University of Beirut": "aub.edu.lb",
    "Tel Aviv University": "tau.ac.il",
    "Hebrew University of Jerusalem": "huji.ac.il",
    "Technion": "technion.ac.il",
    "Weizmann Institute": "weizmann.ac.il",
    "American University in Cairo": "aucegypt.edu",
    "University of Cape Town": "uct.ac.za",
    "University of Witwatersrand": "wits.ac.za",
    "Stellenbosch University": "sun.ac.za",
    
    # Latin America
    "University of São Paulo": "usp.br",
    "University of Campinas": "unicamp.br",
    "Federal University of Rio de Janeiro": "ufrj.br",
    "Universidad Nacional Autónoma de México": "unam.mx",
    "Tecnológico de Monterrey": "tec.mx",
    "Universidad de los Andes": "uniandes.edu.co",
    "Universidad de Chile": "uchile.cl",
    "Pontificia Universidad Católica de Chile": "uc.cl",
    "Universidad de Buenos Aires": "uba.ar",
    
    # Russia & Eastern Europe
    "Moscow State University": "msu.ru",
    "St. Petersburg State University": "spbu.ru",
    "Moscow Institute of Physics and Technology": "mipt.ru",
    "Higher School of Economics": "hse.ru",
    "Novosibirsk State University": "nsu.ru",
    "Charles University": "cuni.cz",
    "University of Warsaw": "uw.edu.pl",
    "Jagiellonian University": "uj.edu.pl",
    "University of Zagreb": "unizg.hr",
    "University of Ljubljana": "uni-lj.si",
    "University of Belgrade": "bg.ac.rs",
    "University of Bucharest": "unibuc.ro",
    
    # New Zealand
    "University of Auckland": "auckland.ac.nz",
    "University of Otago": "otago.ac.nz",
    "Victoria University of Wellington": "wgtn.ac.nz",
    "University of Canterbury": "canterbury.ac.nz",
    "Massey University": "massey.ac.nz",
    "Auckland University of Technology": "aut.ac.nz",
    "University of Waikato": "waikato.ac.nz",
    "Lincoln University": "lincoln.ac.nz",
    
    # Additional Top Global
    "Trinity College Dublin": "tcd.ie",
    "University College Dublin": "ucd.ie",
    "University of Iceland": "hi.is",
    "University of Luxembourg": "uni.lu",
    "University of Malta": "um.edu.mt",
    "University of Cyprus": "ucy.ac.cy",
    "American University of Sharjah": "aus.edu",
    "Qatar University": "qu.edu.qa",
    "United Arab Emirates University": "uaeu.ac.ae",
    "Kuwait University": "ku.edu.kw",
    "Sultan Qaboos University": "squ.edu.om",
    "University of Jordan": "ju.edu.jo",
    "Cairo University": "cu.edu.eg",
    "Alexandria University": "alexu.edu.eg",
    "University of Ghana": "ug.edu.gh",
    "University of Nairobi": "uonbi.ac.ke",
    "Makerere University": "mak.ac.ug",
    "University of Dar es Salaam": "udsm.ac.tz",
    "University of Ibadan": "ui.edu.ng",
    "University of Lagos": "unilag.edu.ng",
    "University of Pretoria": "up.ac.za",
    "Rhodes University": "ru.ac.za",
    "University of KwaZulu-Natal": "ukzn.ac.za",
    "University of the Western Cape": "uwc.ac.za",
    "North-West University": "nwu.ac.za",
    "University of Johannesburg": "uj.ac.za",
    "University of the Free State": "ufs.ac.za"
}

def get_all_universities():
    """Get all universities combined"""
    all_universities = {}
    all_universities.update(US_UNIVERSITIES)
    all_universities.update(CANADIAN_UNIVERSITIES)
    all_universities.update(UK_UNIVERSITIES)
    all_universities.update(EUROPEAN_UNIVERSITIES)
    all_universities.update(INDIAN_UNIVERSITIES)
    all_universities.update(AUSTRALIAN_UNIVERSITIES)
    all_universities.update(GLOBAL_TOP_UNIVERSITIES)
    return all_universities

if __name__ == "__main__":
    all_unis = get_all_universities()
    print(f"US Universities: {len(US_UNIVERSITIES)}")
    print(f"Canadian Universities: {len(CANADIAN_UNIVERSITIES)}")
    print(f"UK Universities: {len(UK_UNIVERSITIES)}")
    print(f"European Universities: {len(EUROPEAN_UNIVERSITIES)}")
    print(f"Indian Universities: {len(INDIAN_UNIVERSITIES)}")
    print(f"Australian Universities: {len(AUSTRALIAN_UNIVERSITIES)}")
    print(f"Global Top Universities: {len(GLOBAL_TOP_UNIVERSITIES)}")
    print(f"\nTOTAL UNIVERSITIES: {len(all_unis)}")
    
    # Check for any duplicates
    from collections import Counter
    domains = [v for v in all_unis.values()]
    duplicates = [item for item, count in Counter(domains).items() if count > 1]
    if duplicates:
        print(f"\nFound {len(duplicates)} duplicate domains")
    else:
        print("\nNo duplicate domains found")