#!/usr/bin/env python3
"""
Comprehensive global employers for business school students
Covering all major regions and industries
"""

# Asia-Pacific Companies
ASIA_PACIFIC_COMPANIES = {
    # Japan
    "Toyota": "toyota.com",
    "Sony": "sony.com",
    "Mitsubishi": "mitsubishi.com",
    "Mitsui": "mitsui.com",
    "Honda": "honda.com",
    "Nissan": "nissan.com",
    "Panasonic": "panasonic.com",
    "SoftBank": "softbank.jp",
    "Rakuten": "rakuten.com",
    "Fast Retailing": "fastretailing.com",
    "Uniqlo": "uniqlo.com",
    "Nintendo": "nintendo.com",
    "Canon": "canon.com",
    "Fujitsu": "fujitsu.com",
    "NTT": "ntt.com",
    "KDDI": "kddi.com",
    "Seven & i Holdings": "7andi.com",
    "Sumitomo": "sumitomo.com",
    "Marubeni": "marubeni.com",
    "Itochu": "itochu.co.jp",
    "Nomura": "nomura.com",
    "Daiwa Securities": "daiwa.co.jp",
    "MUFG": "mufg.jp",
    "Mizuho": "mizuho-fg.com",
    "SMBC": "smbc.co.jp",
    
    # South Korea
    "Samsung": "samsung.com",
    "LG": "lg.com",
    "Hyundai": "hyundai.com",
    "SK Group": "sk.com",
    "Lotte": "lotte.co.kr",
    "POSCO": "posco.com",
    "Hanwha": "hanwha.com",
    "KB Financial": "kbfg.com",
    "Shinhan Financial": "shinhangroup.com",
    "Kakao": "kakaocorp.com",
    "Naver": "navercorp.com",
    "Coupang": "coupang.com",
    "Krafton": "krafton.com",
    "NCsoft": "ncsoft.com",
    "Netmarble": "netmarble.com",
    "Hybe": "hybecorp.com",
    "CJ Group": "cj.net",
    "Amorepacific": "amorepacific.com",
    
    # Singapore
    "DBS Bank": "dbs.com",
    "OCBC Bank": "ocbc.com",
    "UOB": "uob.com.sg",
    "Temasek": "temasek.com.sg",
    "GIC": "gic.com.sg",
    "Singapore Airlines": "singaporeair.com",
    "Grab": "grab.com",
    "Sea Group": "sea.com",
    "Shopee": "shopee.com",
    "CapitaLand": "capitaland.com",
    "Keppel": "kepcorp.com",
    "ST Engineering": "stengg.com",
    "Singtel": "singtel.com",
    "PSA International": "globalpsa.com",
    "Razer": "razer.com",
    "PropertyGuru": "propertyguru.com.sg",
    
    # Hong Kong
    "HSBC": "hsbc.com",
    "Bank of China HK": "bochk.com",
    "Standard Chartered": "sc.com",
    "Cathay Pacific": "cathaypacific.com",
    "Jardine Matheson": "jardines.com",
    "Swire": "swire.com",
    "CK Hutchison": "ckh.com.hk",
    "Li & Fung": "lifung.com",
    "Henderson Land": "hld.com",
    "Sun Hung Kai": "shkp.com",
    "Link REIT": "linkreit.com",
    "Hong Kong Exchanges": "hkex.com.hk",
    "AIA": "aia.com",
    "PCCW": "pccw.com",
    
    # China (International operations)
    "Alibaba": "alibaba.com",
    "Tencent": "tencent.com",
    "ByteDance": "bytedance.com",
    "Baidu": "baidu.com",
    "JD.com": "jd.com",
    "Meituan": "meituan.com",
    "Pinduoduo": "pinduoduo.com",
    "Xiaomi": "mi.com",
    "BYD": "byd.com",
    "Huawei": "huawei.com",
    "Lenovo": "lenovo.com",
    "Haier": "haier.com",
    "NetEase": "netease.com",
    "Didi": "didiglobal.com",
    "NIO": "nio.com",
    "Xpeng": "xiaopeng.com",
    "Li Auto": "lixiang.com",
    "Bilibili": "bilibili.com",
    "Weibo": "weibo.com",
    
    # Southeast Asia
    "Gojek": "gojek.com",
    "Tokopedia": "tokopedia.com",
    "Traveloka": "traveloka.com",
    "Bukalapak": "bukalapak.com",
    "Lazada": "lazada.com",
    "Carousell": "carousell.com",
    "AirAsia": "airasia.com",
    "Axiata": "axiata.com",
    "Sime Darby": "simedarby.com",
    "CP Group": "cpgroupglobal.com",
    "PTT": "pttplc.com",
    "True Corporation": "truecorp.co.th",
    "Central Group": "centralgroup.com",
    "SM Investments": "sminvestments.com",
    "Ayala Corporation": "ayala.com",
    "Jollibee": "jollibee.com.ph",
    "Globe Telecom": "globe.com.ph",
    
    # India (additional)
    "Tata Group": "tata.com",
    "Reliance": "ril.com",
    "Infosys": "infosys.com",
    "Wipro": "wipro.com",
    "HCL": "hcltech.com",
    "Adani Group": "adani.com",
    "Mahindra": "mahindra.com",
    "Bajaj": "bajaj-auto.com",
    "Bharti Airtel": "airtel.in",
    "HDFC Bank": "hdfcbank.com",
    "ICICI Bank": "icicibank.com",
    "Axis Bank": "axisbank.com",
    "Kotak Mahindra": "kotak.com",
    "Larsen & Toubro": "larsentoubro.com",
    "ITC": "itcportal.com",
    "Hindustan Unilever": "hul.co.in",
    "Asian Paints": "asianpaints.com",
    "Maruti Suzuki": "marutisuzuki.com",
    "Ola": "olacabs.com",
    "Zomato": "zomato.com",
    "Swiggy": "swiggy.com",
    "Paytm": "paytm.com",
    "PhonePe": "phonepe.com",
    "Flipkart": "flipkart.com",
    "BYJU'S": "byjus.com",
    "OYO": "oyorooms.com",
    "InMobi": "inmobi.com",
    "Freshworks": "freshworks.com"
}

# Middle East & Gulf Companies
MIDDLE_EAST_COMPANIES = {
    # UAE
    "Emirates": "emirates.com",
    "Etihad Airways": "etihad.com",
    "DP World": "dpworld.com",
    "Emaar": "emaar.com",
    "ADNOC": "adnoc.ae",
    "Mubadala": "mubadala.com",
    "Abu Dhabi Investment Authority": "adia.ae",
    "Dubai Holding": "dubaiholding.com",
    "Majid Al Futtaim": "majidalfuttaim.com",
    "Chalhoub Group": "chalhoubgroup.com",
    "Al-Futtaim": "alfuttaim.com",
    "Etisalat": "etisalat.com",
    "DAMAC": "damacproperties.com",
    "Aldar": "aldar.com",
    "RAK Ceramics": "rakceramics.com",
    
    # Saudi Arabia
    "Saudi Aramco": "aramco.com",
    "SABIC": "sabic.com",
    "STC": "stc.com.sa",
    "NEOM": "neom.com",
    "Saudi Public Investment Fund": "pif.gov.sa",
    "Al Rajhi Bank": "alrajhibank.com.sa",
    "NCB": "alahli.com",
    "Samba": "samba.com",
    "Saudi Electricity": "se.com.sa",
    "Maaden": "maaden.com.sa",
    "Almarai": "almarai.com",
    "Savola": "savola.com",
    "Jarir": "jarir.com",
    "Saudi Airlines": "saudia.com",
    "Red Sea Global": "redseaglobal.com",
    
    # Qatar
    "Qatar Airways": "qatarairways.com",
    "Qatar Investment Authority": "qia.qa",
    "QNB": "qnb.com",
    "Ooredoo": "ooredoo.com",
    "Qatar Petroleum": "qp.com.qa",
    "Qatari Diar": "qataridiar.com",
    "Doha Bank": "dohabank.com",
    "Commercial Bank of Qatar": "cbq.qa",
    
    # Other Gulf
    "Kuwait Investment Authority": "kia.gov.kw",
    "National Bank of Kuwait": "nbk.com",
    "Zain": "zain.com",
    "Investcorp": "investcorp.com",
    "Gulf Bank": "e-gulfbank.com",
    "Bahrain Mumtalakat": "mumtalakat.bh",
    "Bank Muscat": "bankmuscat.com",
    
    # Turkey
    "Turkish Airlines": "turkishairlines.com",
    "Koç Holding": "koc.com.tr",
    "Sabancı Holding": "sabanci.com",
    "Turkcell": "turkcell.com.tr",
    "Garanti BBVA": "garantibbva.com.tr",
    "Akbank": "akbank.com",
    "İşbank": "isbank.com.tr",
    
    # Israel
    "Check Point": "checkpoint.com",
    "Wix": "wix.com",
    "Fiverr": "fiverr.com",
    "Monday.com": "monday.com",
    "Taboola": "taboola.com",
    "Outbrain": "outbrain.com",
    "IronSource": "ironsrc.com",
    "SimilarWeb": "similarweb.com"
}

# Latin American Companies
LATIN_AMERICAN_COMPANIES = {
    # Brazil
    "Itaú Unibanco": "itau.com.br",
    "Bradesco": "bradesco.com.br",
    "Banco do Brasil": "bb.com.br",
    "Petrobras": "petrobras.com.br",
    "Vale": "vale.com",
    "Ambev": "ambev.com.br",
    "JBS": "jbs.com.br",
    "3G Capital": "3g-capital.com",
    "BTG Pactual": "btgpactual.com",
    "XP Inc": "xpinc.com",
    "Stone": "stone.co",
    "PagSeguro": "pagseguro.com.br",
    "Nubank": "nubank.com.br",
    "iFood": "ifood.com.br",
    "Movile": "movile.com",
    "Wildlife Studios": "wildlifestudios.com",
    "VTEX": "vtex.com",
    "TOTVS": "totvs.com",
    "Natura": "natura.com.br",
    "Magazine Luiza": "magazineluiza.com.br",
    "B2W": "b2w.io",
    "Localiza": "localiza.com",
    "Embraer": "embraer.com",
    "Gerdau": "gerdau.com",
    
    # Mexico
    "América Móvil": "americamovil.com",
    "FEMSA": "femsa.com",
    "Grupo Bimbo": "grupobimbo.com",
    "Cemex": "cemex.com",
    "Grupo México": "gmexico.com",
    "Banorte": "banorte.com",
    "OXXO": "oxxo.com",
    "Televisa": "televisa.com",
    "Grupo Salinas": "gruposalinas.com",
    "Cinépolis": "cinepolis.com",
    "Softtek": "softtek.com",
    "Kueski": "kueski.com",
    "Clip": "clip.mx",
    "Kavak": "kavak.com",
    "Bitso": "bitso.com",
    
    # Argentina
    "Mercado Libre": "mercadolibre.com",
    "Globant": "globant.com",
    "Despegar": "despegar.com",
    "OLX": "olx.com.ar",
    "Ualá": "uala.com.ar",
    "Banco Galicia": "bancogalicia.com",
    "YPF": "ypf.com",
    "Techint": "techint.com",
    
    # Chile
    "LATAM Airlines": "latamairlines.com",
    "Banco Santander Chile": "santander.cl",
    "Falabella": "falabella.com",
    "Cencosud": "cencosud.com",
    "ENAP": "enap.cl",
    "Cornershop": "cornershop.com",
    "NotCo": "notco.com",
    
    # Colombia
    "Avianca": "avianca.com",
    "Bancolombia": "bancolombia.com",
    "Ecopetrol": "ecopetrol.com.co",
    "Grupo Éxito": "grupoexito.com.co",
    "Rappi": "rappi.com",
    "Davivienda": "davivienda.com",
    
    # Peru
    "Interbank": "interbank.pe",
    "Alicorp": "alicorp.com.pe",
    "Southern Copper": "southerncoppercorp.com",
    "Credicorp": "credicorp.com"
}

# African Companies
AFRICAN_COMPANIES = {
    # South Africa
    "Naspers": "naspers.com",
    "Prosus": "prosus.com",
    "Standard Bank": "standardbank.com",
    "FirstRand": "firstrand.co.za",
    "MTN Group": "mtn.com",
    "Vodacom": "vodacom.com",
    "Discovery": "discovery.co.za",
    "Sasol": "sasol.com",
    "Anglo American": "angloamerican.com",
    "Shoprite": "shoprite.co.za",
    "Pick n Pay": "pnp.co.za",
    "Woolworths SA": "woolworths.co.za",
    "Capitec": "capitecbank.co.za",
    "Sanlam": "sanlam.com",
    "Old Mutual": "oldmutual.com",
    "Bidvest": "bidvest.com",
    "Aspen Pharmacare": "aspenpharma.com",
    "Remgro": "remgro.com",
    
    # Nigeria
    "Dangote Group": "dangote.com",
    "Access Bank": "accessbankplc.com",
    "Zenith Bank": "zenithbank.com",
    "GTBank": "gtbank.com",
    "First Bank Nigeria": "firstbanknigeria.com",
    "Nigerian National Petroleum": "nnpcgroup.com",
    "Airtel Africa": "airtel.africa",
    "Glo Mobile": "gloworld.com",
    "Interswitch": "interswitchgroup.com",
    "Flutterwave": "flutterwave.com",
    "Paystack": "paystack.com",
    "Andela": "andela.com",
    "Jumia": "jumia.com",
    
    # Kenya
    "Safaricom": "safaricom.co.ke",
    "M-Pesa": "vodafone.com/about/m-pesa",
    "Kenya Commercial Bank": "kcbgroup.com",
    "Equity Bank": "equitygroupholdings.com",
    "East African Breweries": "eabl.com",
    
    # Egypt
    "Commercial International Bank": "cibeg.com",
    "Orascom": "orascom.com",
    "EFG Hermes": "efghermes.com",
    "Telecom Egypt": "te.eg",
    
    # Morocco
    "OCP Group": "ocpgroup.ma",
    "Attijariwafa Bank": "attijariwafabank.com",
    "Maroc Telecom": "iam.ma",
    "Royal Air Maroc": "royalairmaroc.com",
    
    # Pan-African
    "Ecobank": "ecobank.com",
    "Atlas Mara": "atlasmara.com",
    "Africa Finance Corporation": "africafc.org"
}

# Luxury, Retail & Consumer Goods
LUXURY_RETAIL_COMPANIES = {
    # Luxury
    "LVMH": "lvmh.com",
    "Kering": "kering.com",
    "Hermès": "hermes.com",
    "Chanel": "chanel.com",
    "Richemont": "richemont.com",
    "Prada": "pradagroup.com",
    "Burberry": "burberryplc.com",
    "Moncler": "monclergroup.com",
    "Ferragamo": "ferragamo.com",
    "Tod's": "todsgroup.com",
    "Bulgari": "bulgari.com",
    "Tiffany & Co": "tiffany.com",
    "Cartier": "cartier.com",
    "Van Cleef & Arpels": "vancleefarpels.com",
    "Rolex": "rolex.com",
    "Patek Philippe": "patek.com",
    "Audemars Piguet": "audemarspiguet.com",
    "Swatch Group": "swatchgroup.com",
    
    # Beauty & Personal Care
    "L'Oréal": "loreal.com",
    "Estée Lauder": "elcompanies.com",
    "Procter & Gamble": "pg.com",
    "Unilever": "unilever.com",
    "Shiseido": "shiseido.com",
    "Coty": "coty.com",
    "Revlon": "revlon.com",
    "Avon": "avon.com",
    "Beiersdorf": "beiersdorf.com",
    "Kao": "kao.com",
    "Henkel": "henkel.com",
    "Church & Dwight": "churchdwight.com",
    "Colgate-Palmolive": "colgatepalmolive.com",
    
    # Fashion & Sportswear
    "Nike": "nike.com",
    "Adidas": "adidas.com",
    "Puma": "puma.com",
    "Under Armour": "underarmour.com",
    "Lululemon": "lululemon.com",
    "VF Corporation": "vfc.com",
    "Ralph Lauren": "ralphlauren.com",
    "Tommy Hilfiger": "tommy.com",
    "Calvin Klein": "calvinklein.com",
    "Gap": "gap.com",
    "H&M": "hm.com",
    "Zara": "zara.com",
    "Inditex": "inditex.com",
    "Fast Retailing": "fastretailing.com",
    "Primark": "primark.com",
    "ASOS": "asosplc.com",
    "Zalando": "zalando.com",
    "Farfetch": "farfetch.com",
    "Revolve": "revolve.com",
    "Shein": "shein.com",
    
    # Food & Beverage
    "Nestlé": "nestle.com",
    "PepsiCo": "pepsico.com",
    "Coca-Cola": "coca-colacompany.com",
    "Mondelez": "mondelezinternational.com",
    "Kraft Heinz": "kraftheinzcompany.com",
    "General Mills": "generalmills.com",
    "Kellogg's": "kelloggs.com",
    "Mars": "mars.com",
    "Danone": "danone.com",
    "AB InBev": "ab-inbev.com",
    "Diageo": "diageo.com",
    "Pernod Ricard": "pernod-ricard.com",
    "Heineken": "theheinekencompany.com",
    "Carlsberg": "carlsberggroup.com",
    "Brown-Forman": "brown-forman.com",
    "Constellation Brands": "cbrands.com",
    "Monster Beverage": "monsterbevcorp.com",
    "Red Bull": "redbull.com",
    "Starbucks": "starbucks.com",
    "McDonald's": "mcdonalds.com",
    "Yum! Brands": "yum.com",
    "Restaurant Brands": "rbi.com",
    "Domino's": "dominos.com",
    "Chipotle": "chipotle.com",
    
    # Retail
    "Walmart": "walmart.com",
    "Amazon": "amazon.com",
    "Costco": "costco.com",
    "Home Depot": "homedepot.com",
    "Target": "target.com",
    "CVS": "cvs.com",
    "Walgreens": "walgreensbootsalliance.com",
    "Kroger": "kroger.com",
    "Tesco": "tesco.com",
    "Carrefour": "carrefour.com",
    "Aldi": "aldi.com",
    "Lidl": "lidl.com",
    "IKEA": "ikea.com",
    "Best Buy": "bestbuy.com",
    "Lowe's": "lowes.com",
    "TJX": "tjx.com",
    "Ross Stores": "rossstores.com",
    "Dollar General": "dollargeneral.com",
    "Sephora": "sephora.com",
    "Ulta Beauty": "ulta.com"
}

# Pharma, Healthcare & Medical Devices
PHARMA_HEALTHCARE_COMPANIES = {
    # Big Pharma
    "Johnson & Johnson": "jnj.com",
    "Roche": "roche.com",
    "Pfizer": "pfizer.com",
    "Novartis": "novartis.com",
    "Merck": "merck.com",
    "AbbVie": "abbvie.com",
    "Sanofi": "sanofi.com",
    "GlaxoSmithKline": "gsk.com",
    "AstraZeneca": "astrazeneca.com",
    "Bristol Myers Squibb": "bms.com",
    "Eli Lilly": "lilly.com",
    "Amgen": "amgen.com",
    "Gilead Sciences": "gilead.com",
    "Regeneron": "regeneron.com",
    "Vertex": "vrtx.com",
    "Biogen": "biogen.com",
    "Moderna": "modernatx.com",
    "BioNTech": "biontech.de",
    "Novo Nordisk": "novonordisk.com",
    "Takeda": "takeda.com",
    "Bayer": "bayer.com",
    "Boehringer Ingelheim": "boehringer-ingelheim.com",
    "Teva": "tevapharm.com",
    "Mylan": "mylan.com",
    
    # Medical Devices
    "Medtronic": "medtronic.com",
    "Abbott": "abbott.com",
    "Thermo Fisher": "thermofisher.com",
    "Danaher": "danaher.com",
    "Becton Dickinson": "bd.com",
    "Stryker": "stryker.com",
    "Boston Scientific": "bostonscientific.com",
    "Edwards Lifesciences": "edwards.com",
    "Zimmer Biomet": "zimmerbiomet.com",
    "Intuitive Surgical": "intuitive.com",
    "Align Technology": "aligntech.com",
    "ResMed": "resmed.com",
    "Illumina": "illumina.com",
    "Agilent": "agilent.com",
    "PerkinElmer": "perkinelmer.com",
    "Waters Corporation": "waters.com",
    "Bio-Rad": "bio-rad.com",
    "Bruker": "bruker.com",
    
    # Healthcare Services
    "UnitedHealth": "unitedhealthgroup.com",
    "Anthem": "antheminc.com",
    "CVS Health": "cvshealth.com",
    "Cigna": "cigna.com",
    "Humana": "humana.com",
    "Centene": "centene.com",
    "HCA Healthcare": "hcahealthcare.com",
    "Tenet Healthcare": "tenethealth.com",
    "Universal Health Services": "uhsinc.com",
    "DaVita": "davita.com",
    "Fresenius": "fresenius.com",
    "Quest Diagnostics": "questdiagnostics.com",
    "LabCorp": "labcorp.com",
    "McKesson": "mckesson.com",
    "AmerisourceBergen": "amerisourcebergen.com",
    "Cardinal Health": "cardinalhealth.com",
    
    # Digital Health
    "Teladoc": "teladochealth.com",
    "Amwell": "amwell.com",
    "Babylon Health": "babylonhealth.com",
    "Doximity": "doximity.com",
    "GoodRx": "goodrx.com",
    "23andMe": "23andme.com",
    "Veeva Systems": "veeva.com",
    "Cerner": "cerner.com",
    "Epic Systems": "epic.com",
    "Athenahealth": "athenahealth.com"
}

# Energy, Infrastructure & Industrials
ENERGY_INFRASTRUCTURE_COMPANIES = {
    # Oil & Gas
    "ExxonMobil": "exxonmobil.com",
    "Chevron": "chevron.com",
    "Shell": "shell.com",
    "BP": "bp.com",
    "TotalEnergies": "totalenergies.com",
    "ConocoPhillips": "conocophillips.com",
    "Eni": "eni.com",
    "Equinor": "equinor.com",
    "Repsol": "repsol.com",
    "Marathon Petroleum": "marathonpetroleum.com",
    "Valero": "valero.com",
    "Phillips 66": "phillips66.com",
    "Occidental": "oxy.com",
    "EOG Resources": "eogresources.com",
    "Schlumberger": "slb.com",
    "Halliburton": "halliburton.com",
    "Baker Hughes": "bakerhughes.com",
    
    # Utilities & Power
    "NextEra Energy": "nexteraenergy.com",
    "Enel": "enel.com",
    "Iberdrola": "iberdrola.com",
    "EDF": "edf.fr",
    "Engie": "engie.com",
    "E.ON": "eon.com",
    "RWE": "rwe.com",
    "Dominion Energy": "dominionenergy.com",
    "Duke Energy": "duke-energy.com",
    "Southern Company": "southerncompany.com",
    "Exelon": "exeloncorp.com",
    "National Grid": "nationalgrid.com",
    "SSE": "sse.com",
    "Centrica": "centrica.com",
    "Orsted": "orsted.com",
    "Vestas": "vestas.com",
    "Siemens Gamesa": "siemensgamesa.com",
    "First Solar": "firstsolar.com",
    "Enphase": "enphase.com",
    "SunPower": "sunpower.com",
    
    # Industrial & Engineering
    "General Electric": "ge.com",
    "Siemens": "siemens.com",
    "ABB": "abb.com",
    "Schneider Electric": "se.com",
    "Honeywell": "honeywell.com",
    "3M": "3m.com",
    "Caterpillar": "caterpillar.com",
    "John Deere": "deere.com",
    "Emerson": "emerson.com",
    "Illinois Tool Works": "itw.com",
    "Parker Hannifin": "parker.com",
    "Eaton": "eaton.com",
    "Johnson Controls": "johnsoncontrols.com",
    "Rockwell Automation": "rockwellautomation.com",
    "Fortive": "fortive.com",
    "Danaher": "danaher.com",
    "Roper Technologies": "ropertech.com",
    "Carrier": "carrier.com",
    "Otis": "otis.com",
    "Trane": "trane.com",
    
    # Infrastructure & Construction
    "Vinci": "vinci.com",
    "Bouygues": "bouygues.com",
    "ACS Group": "grupoacs.com",
    "Skanska": "skanska.com",
    "Bechtel": "bechtel.com",
    "Fluor": "fluor.com",
    "Jacobs": "jacobs.com",
    "AECOM": "aecom.com",
    "WSP Global": "wsp.com",
    "SNC-Lavalin": "snclavalin.com",
    "Worley": "worley.com",
    "Wood Group": "woodplc.com",
    "KBR": "kbr.com",
    "Quanta Services": "quantaservices.com",
    
    # Metals & Mining
    "BHP": "bhp.com",
    "Rio Tinto": "riotinto.com",
    "Vale": "vale.com",
    "Glencore": "glencore.com",
    "Anglo American": "angloamerican.com",
    "Freeport-McMoRan": "fcx.com",
    "Newmont": "newmont.com",
    "Barrick Gold": "barrick.com",
    "Nucor": "nucor.com",
    "ArcelorMittal": "arcelormittal.com",
    "Alcoa": "alcoa.com",
    "Norsk Hydro": "hydro.com",
    "Teck Resources": "teck.com",
    "First Quantum": "first-quantum.com"
}

# Government, Multilateral & NGOs
GOVERNMENT_MULTILATERAL_ORGS = {
    # Multilateral Organizations
    "World Bank": "worldbank.org",
    "International Monetary Fund": "imf.org",
    "United Nations": "un.org",
    "World Trade Organization": "wto.org",
    "World Health Organization": "who.int",
    "International Finance Corporation": "ifc.org",
    "Asian Development Bank": "adb.org",
    "African Development Bank": "afdb.org",
    "Inter-American Development Bank": "iadb.org",
    "European Bank for Reconstruction": "ebrd.com",
    "European Investment Bank": "eib.org",
    "OECD": "oecd.org",
    "Bank for International Settlements": "bis.org",
    
    # Central Banks
    "Federal Reserve": "federalreserve.gov",
    "European Central Bank": "ecb.europa.eu",
    "Bank of England": "bankofengland.co.uk",
    "Bank of Japan": "boj.or.jp",
    "People's Bank of China": "pbc.gov.cn",
    "Reserve Bank of India": "rbi.org.in",
    "Bank of Canada": "bankofcanada.ca",
    "Reserve Bank of Australia": "rba.gov.au",
    "Swiss National Bank": "snb.ch",
    "Bundesbank": "bundesbank.de",
    "Banque de France": "banque-france.fr",
    "Bank of Italy": "bancaditalia.it",
    "Bank of Spain": "bde.es",
    "Riksbank": "riksbank.se",
    "Norges Bank": "norges-bank.no",
    
    # Development Finance
    "IFC": "ifc.org",
    "CDC Group": "cdcgroup.com",
    "Proparco": "proparco.fr",
    "DEG": "deginvest.de",
    "FMO": "fmo.nl",
    "Norfund": "norfund.no",
    "Swedfund": "swedfund.se",
    "OPIC": "opic.gov",
    "Development Bank of Japan": "dbj.jp",
    "KfW": "kfw.de",
    "CAF": "caf.com",
    "Islamic Development Bank": "isdb.org",
    
    # Major NGOs
    "Bill & Melinda Gates Foundation": "gatesfoundation.org",
    "Ford Foundation": "fordfoundation.org",
    "Rockefeller Foundation": "rockefellerfoundation.org",
    "MacArthur Foundation": "macfound.org",
    "Open Society Foundations": "opensocietyfoundations.org",
    "Clinton Foundation": "clintonfoundation.org",
    "Carter Center": "cartercenter.org",
    "Brookings Institution": "brookings.edu",
    "Council on Foreign Relations": "cfr.org",
    "Chatham House": "chathamhouse.org",
    "RAND Corporation": "rand.org",
    "McKinsey Global Institute": "mckinsey.com/mgi",
    
    # International NGOs
    "Red Cross": "icrc.org",
    "Doctors Without Borders": "msf.org",
    "Save the Children": "savethechildren.org",
    "Oxfam": "oxfam.org",
    "CARE International": "care-international.org",
    "World Wildlife Fund": "worldwildlife.org",
    "Greenpeace": "greenpeace.org",
    "Amnesty International": "amnesty.org",
    "Human Rights Watch": "hrw.org"
}

# Boutique Consulting & Banking
BOUTIQUE_FIRMS = {
    # Boutique Investment Banks
    "Evercore": "evercore.com",
    "Lazard": "lazard.com",
    "Centerview Partners": "centerviewpartners.com",
    "Moelis & Company": "moelis.com",
    "Perella Weinberg": "pwpartners.com",
    "Rothschild & Co": "rothschildandco.com",
    "Greenhill": "greenhill.com",
    "Houlihan Lokey": "hl.com",
    "Jefferies": "jefferies.com",
    "Piper Sandler": "pipersandler.com",
    "William Blair": "williamblair.com",
    "Stifel": "stifel.com",
    "Robert W. Baird": "rwbaird.com",
    "Lincoln International": "lincolninternational.com",
    "Harris Williams": "harriswilliams.com",
    "Solomon Partners": "solomonpartners.com",
    "Guggenheim": "guggenheimpartners.com",
    "Qatalyst": "qatalyst.com",
    "Allen & Company": "allenco.com",
    "Raine Ventures": "raine.com",
    
    # Boutique Strategy Consulting
    "L.E.K. Consulting": "lek.com",
    "Oliver Wyman": "oliverwyman.com",
    "Roland Berger": "rolandberger.com",
    "Simon-Kucher": "simon-kucher.com",
    "Kearney": "kearney.com",
    "Strategy&": "strategyand.pwc.com",
    "Monitor Deloitte": "deloitte.com",
    "Parthenon-EY": "parthenon.ey.com",
    "AlixPartners": "alixpartners.com",
    "FTI Consulting": "fticonsulting.com",
    "Alvarez & Marsal": "alvarezandmarsal.com",
    "Analysis Group": "analysisgroup.com",
    "Charles River Associates": "crai.com",
    "Cornerstone Research": "cornerstone.com",
    "NERA": "nera.com",
    "Brattle Group": "brattle.com",
    
    # Specialized Consulting
    "ZS Associates": "zs.com",
    "Putnam Associates": "putassoc.com",
    "Clarion Healthcare": "clarionhealthcare.com",
    "Trinity Partners": "trinitypartners.com",
    "Health Advances": "healthadvances.com",
    "ClearView Healthcare": "clearviewhcp.com",
    "Campbell Alliance": "campbellalliance.com",
    "Navigant": "navigant.com",
    "Huron Consulting": "huronconsultinggroup.com",
    "West Monroe": "westmonroe.com",
    "North Highland": "northhighland.com",
    "Slalom": "slalom.com",
    "Point B": "pointb.com",
    "Pariveda": "parivedasolutions.com",
    
    # Restructuring & Turnaround
    "Alix Partners": "alixpartners.com",
    "Alvarez & Marsal": "alvarezandmarsal.com",
    "FTI Consulting": "fticonsulting.com",
    "Houlihan Lokey": "hl.com",
    "PJT Partners": "pjtpartners.com",
    "Ducera": "ducerapartners.com",
    "Miller Buckfire": "stifel.com",
    "Gordian Group": "gordiangroup.com"
}

# Media, Entertainment & Sports
MEDIA_ENTERTAINMENT_COMPANIES = {
    # Media Conglomerates
    "Disney": "disney.com",
    "Warner Bros Discovery": "wbd.com",
    "Comcast NBCUniversal": "comcastcorporation.com",
    "Paramount": "paramount.com",
    "Sony Entertainment": "sony.com",
    "Netflix": "netflix.com",
    "Amazon Prime": "amazon.com",
    "Apple TV+": "apple.com",
    "ViacomCBS": "viaconcbs.com",
    "Fox Corporation": "foxcorporation.com",
    "Discovery": "discovery.com",
    "AMC Networks": "amcnetworks.com",
    "Lionsgate": "lionsgate.com",
    "MGM": "mgm.com",
    
    # Music & Streaming
    "Spotify": "spotify.com",
    "Universal Music": "universalmusic.com",
    "Sony Music": "sonymusic.com",
    "Warner Music": "wmg.com",
    "Live Nation": "livenationentertainment.com",
    "SiriusXM": "siriusxm.com",
    "Pandora": "pandora.com",
    "iHeartMedia": "iheartmedia.com",
    "TuneIn": "tunein.com",
    
    # Publishing
    "News Corp": "newscorp.com",
    "New York Times": "nytco.com",
    "Washington Post": "washingtonpost.com",
    "Wall Street Journal": "wsj.com",
    "Financial Times": "ft.com",
    "Bloomberg": "bloomberg.com",
    "Reuters": "reuters.com",
    "Associated Press": "ap.org",
    "Condé Nast": "condenast.com",
    "Hearst": "hearst.com",
    "Meredith": "meredith.com",
    "Axel Springer": "axelspringer.com",
    "Bertelsmann": "bertelsmann.com",
    "Pearson": "pearson.com",
    "Penguin Random House": "penguinrandomhouse.com",
    "HarperCollins": "harpercollins.com",
    "Hachette": "hachette.com",
    "Simon & Schuster": "simonandschuster.com",
    
    # Advertising & Marketing
    "WPP": "wpp.com",
    "Omnicom": "omnicomgroup.com",
    "Publicis": "publicisgroupe.com",
    "IPG": "interpublic.com",
    "Dentsu": "dentsu.com",
    "Havas": "havas.com",
    "S4 Capital": "s4capital.com",
    "MDC Partners": "mdc-partners.com",
    
    # Gaming
    "Activision Blizzard": "activisionblizzard.com",
    "Electronic Arts": "ea.com",
    "Take-Two Interactive": "take2games.com",
    "Ubisoft": "ubisoft.com",
    "Nintendo": "nintendo.com",
    "Sony PlayStation": "playstation.com",
    "Microsoft Xbox": "xbox.com",
    "Epic Games": "epicgames.com",
    "Valve": "valvesoftware.com",
    "Roblox": "roblox.com",
    "Unity": "unity.com",
    "Zynga": "zynga.com",
    "Supercell": "supercell.com",
    "King": "king.com",
    "Riot Games": "riotgames.com",
    "Blizzard": "blizzard.com",
    
    # Sports
    "NFL": "nfl.com",
    "NBA": "nba.com",
    "MLB": "mlb.com",
    "NHL": "nhl.com",
    "FIFA": "fifa.com",
    "UEFA": "uefa.com",
    "Premier League": "premierleague.com",
    "Formula 1": "formula1.com",
    "ESPN": "espn.com",
    "Sky Sports": "skysports.com",
    "DAZN": "dazn.com",
    "Fanatics": "fanatics.com",
    "DraftKings": "draftkings.com",
    "FanDuel": "fanduel.com",
    "Caesars": "caesars.com",
    "MGM Resorts": "mgmresorts.com",
    
    # Talent Agencies
    "CAA": "caa.com",
    "WME": "wmeagency.com",
    "UTA": "unitedtalent.com",
    "ICM": "icmpartners.com",
    "Endeavor": "endeavorco.com"
}

# Real Estate & PropTech
REAL_ESTATE_COMPANIES = {
    # Commercial Real Estate Services
    "CBRE": "cbre.com",
    "JLL": "jll.com",
    "Cushman & Wakefield": "cushmanwakefield.com",
    "Colliers": "colliers.com",
    "Newmark": "nmrk.com",
    "Knight Frank": "knightfrank.com",
    "Savills": "savills.com",
    "DTZ": "dtz.com",
    
    # REITs & Developers
    "Blackstone Real Estate": "blackstone.com",
    "Brookfield Property": "brookfieldproperties.com",
    "Prologis": "prologis.com",
    "Simon Property": "simon.com",
    "Equity Residential": "equityapartments.com",
    "AvalonBay": "avaloncommunities.com",
    "Public Storage": "publicstorage.com",
    "Welltower": "welltower.com",
    "Digital Realty": "digitalrealty.com",
    "American Tower": "americantower.com",
    "Crown Castle": "crowncastle.com",
    "Equinix": "equinix.com",
    "Realty Income": "realtyincome.com",
    "VICI Properties": "viciproperties.com",
    "Alexandria Real Estate": "are.com",
    "Boston Properties": "bostonproperties.com",
    "Vornado": "vno.com",
    "SL Green": "slgreen.com",
    "Kimco": "kimcorealty.com",
    "Regency Centers": "regencycenters.com",
    
    # Residential
    "Lennar": "lennar.com",
    "D.R. Horton": "drhorton.com",
    "PulteGroup": "pulte.com",
    "Toll Brothers": "tollbrothers.com",
    "KB Home": "kbhome.com",
    "Hovnanian": "khov.com",
    "Taylor Morrison": "taylormorrison.com",
    "Meritage Homes": "meritagehomes.com",
    
    # PropTech
    "CoStar": "costar.com",
    "Zillow": "zillow.com",
    "Redfin": "redfin.com",
    "Compass": "compass.com",
    "Opendoor": "opendoor.com",
    "Offerpad": "offerpad.com",
    "Knock": "knock.com",
    "Flyhomes": "flyhomes.com",
    "Better.com": "better.com",
    "Roofstock": "roofstock.com",
    "Cadre": "cadre.com",
    "Fundrise": "fundrise.com",
    "RealtyMogul": "realtymogul.com",
    "WeWork": "wework.com",
    "IWG": "iwgplc.com",
    "Knotel": "knotel.com",
    "Industrious": "industriousoffice.com"
}

def get_all_comprehensive_companies():
    """Return all companies from comprehensive expansion"""
    all_companies = {}
    all_companies.update(ASIA_PACIFIC_COMPANIES)
    all_companies.update(MIDDLE_EAST_COMPANIES)
    all_companies.update(LATIN_AMERICAN_COMPANIES)
    all_companies.update(AFRICAN_COMPANIES)
    all_companies.update(LUXURY_RETAIL_COMPANIES)
    all_companies.update(PHARMA_HEALTHCARE_COMPANIES)
    all_companies.update(ENERGY_INFRASTRUCTURE_COMPANIES)
    all_companies.update(GOVERNMENT_MULTILATERAL_ORGS)
    all_companies.update(BOUTIQUE_FIRMS)
    all_companies.update(MEDIA_ENTERTAINMENT_COMPANIES)
    all_companies.update(REAL_ESTATE_COMPANIES)
    return all_companies

if __name__ == "__main__":
    all_companies = get_all_comprehensive_companies()
    print(f"Asia-Pacific: {len(ASIA_PACIFIC_COMPANIES)}")
    print(f"Middle East: {len(MIDDLE_EAST_COMPANIES)}")
    print(f"Latin America: {len(LATIN_AMERICAN_COMPANIES)}")
    print(f"Africa: {len(AFRICAN_COMPANIES)}")
    print(f"Luxury/Retail: {len(LUXURY_RETAIL_COMPANIES)}")
    print(f"Pharma/Healthcare: {len(PHARMA_HEALTHCARE_COMPANIES)}")
    print(f"Energy/Infrastructure: {len(ENERGY_INFRASTRUCTURE_COMPANIES)}")
    print(f"Government/Multilateral: {len(GOVERNMENT_MULTILATERAL_ORGS)}")
    print(f"Boutique Firms: {len(BOUTIQUE_FIRMS)}")
    print(f"Media/Entertainment: {len(MEDIA_ENTERTAINMENT_COMPANIES)}")
    print(f"Real Estate: {len(REAL_ESTATE_COMPANIES)}")
    print(f"\nTOTAL NEW ORGANIZATIONS: {len(all_companies)}")