#!/usr/bin/env python3
"""
Master list of missing MBA employer logos based on parallel Task analysis
Consolidating results from A-Z analysis plus verification
"""

def get_master_missing_list():
    """Master list of verified missing MBA employers"""
    return [
        # VERIFIED MISSING FROM CHECK
        "BCG", "Boston Consulting Group",
        "Booz Allen Hamilton", 
        "Warburg Pincus",
        "Silver Lake", 
        "Thoma Bravo",
        "AB InBev",
        "Estee Lauder",
        "Johnson & Johnson",
        "Bristol Myers Squibb",
        "Eli Lilly",
        
        # HIGH PRIORITY MISSING FROM TASK ANALYSIS (A-E)
        "Anthropic",
        "Alchemy",
        "Anduril", 
        "Airtable",
        "Amplitude",
        "Asana",
        "Auth0",
        "AutoDesk",
        "Benchling",
        "BetterUp",
        "BigCommerce", 
        "Brex",
        "Calendly",
        "Canva",
        "Chime",
        "Clearbit",
        "Clubhouse",
        "CockroachDB",
        "Coinbase",
        "Contentful",
        "Convoy",
        "CrowdStrike", 
        "DataRobot",
        "DoorDash",
        "Discord",
        "Domo",
        "DigitalOcean",
        "Dribbble",
        "Dropbox Business",
        
        # F-J COMPANIES
        "Figma",
        "Freshworks",
        "GitHub",
        "GitLab", 
        "GoCardless",
        "Grammarly",
        "Gusto",
        "HashiCorp",
        "HubSpot",
        "Indeed",
        "Instacart",
        "Intercom",
        "JFrog",
        
        # K-O COMPANIES  
        "Klarna",
        "Klaviyo",
        "LaunchDarkly",
        "Lime",
        "Linear",
        "Loom",
        "Miro",
        "Monday.com",
        "Notion",
        "Nextdoor",
        "NewRelic",
        "Netlify",
        
        # P-T COMPANIES
        "PagerDuty",
        "Plaid", 
        "Postman",
        "Razorpay",
        "Robinhood",
        "Segment",
        "SendGrid", 
        "Shopify",
        "Slack",
        "Snowflake",
        "SoFi",
        "Splunk",
        "Square",
        "Stripe",
        "Sumo Logic",
        "TikTok",
        "Twilio",
        "Toast",
        
        # U-Z COMPANIES
        "Unity",
        "Veeva Systems", 
        "Vercel",
        "Webflow",
        "Wiz",
        "Zapier",
        "Zendesk",
        "Zoom",
        
        # ADDITIONAL HIGH-VALUE MBA TARGETS
        "Databricks",
        "Palantir",
        "Roblox",
        "Epic Games",
        "Rivian",
        "Lucid Motors",
        "SpaceX",
        "Blue Origin",
        "Rocket Lab",
        "Relativity Space",
        "Virgin Galactic",
        "ChargePoint",
        "EVgo",
        "Sunrun",
        "NextEra Energy",
        "First Solar",
        "Vestas",
        "Siemens Gamesa",
        "Tesla Energy",
        "Enphase Energy",
        "SolarEdge",
        
        # FINTECH MISSING
        "Affirm",
        "Afterpay", 
        "Wise",
        "Revolut",
        "N26",
        "Monzo",
        "Starling Bank",
        "Varo",
        "Current",
        "Dave",
        "Earnin",
        "MoneyLion",
        "Webull",
        "eToro", 
        "Plus500",
        "Kraken",
        "Gemini",
        "Crypto.com",
        "BlockFi",
        "Celsius Network",
        "Nexo",
        "Circle",
        "Ripple",
        
        # MEDIA & ENTERTAINMENT
        "TuneIn",
        "iHeartRadio",
        "Bandcamp", 
        "SoundCloud",
        "Deezer",
        "Tidal",
        "Activision Blizzard",
        "Electronic Arts", 
        "Take-Two",
        "Ubisoft",
        "Valve",
        "Riot Games",
        "Supercell",
        "Unity Technologies",
        
        # LOGISTICS & SUPPLY CHAIN
        "Maersk",
        "MSC",
        "CMA CGM",
        "Hapag-Lloyd",
        "DB Schenker",
        "Kuehne + Nagel",
        "DSV",
        "C.H. Robinson",
        "Expeditors",
        "XPO Logistics",
        "J.B. Hunt",
        "Schneider National",
        
        # REAL ESTATE & PROPTECH
        "CBRE",
        "JLL",
        "Cushman & Wakefield",
        "Colliers",
        "Marcus & Millichap",
        "Prologis",
        "Public Storage",
        "Welltower",
        "Equity Residential",
        "AvalonBay",
        "WeWork",
        "IWG",
        "Industrious",
        "Zillow",
        "Redfin", 
        "Opendoor",
        "Compass",
        "Vrbo",
        "Booking.com",
        "Tripadvisor",
        
        # INSURANCE & ASSET MANAGEMENT
        "AIG",
        "Chubb",
        "Travelers",
        "Progressive",
        "Geico",
        "State Farm",
        "Allstate",
        "Liberty Mutual",
        "MetLife",
        "Prudential Financial",
        "New York Life",
        "Northwestern Mutual",
        "BlackRock",
        "Vanguard",
        "State Street",
        "Invesco",
        "Franklin Templeton",
        "T. Rowe Price",
        
        # AUTOMOTIVE & MOBILITY
        "Stellantis",
        "Renault",
        "Peugeot",
        "Citroen", 
        "Maserati",
        "Lamborghini",
        "Bentley",
        "Rolls-Royce Motor Cars",
        "McLaren",
        "Aston Martin",
        "Volvo Cars",
        "Polestar",
        "Genesis",
        "Waymo",
        "Cruise",
        "Aurora",
        "Zoox",
        "Nuro",
        "TuSimple",
        "Embark",
        "Kodiak Robotics",
        
        # ADDITIONAL TECH UNICORNS
        "Bytedance",
        "Xiaomi",
        "DJI",
        "Oppo", 
        "Vivo",
        "OnePlus",
        "Nothing",
        "Realme",
        "Honor",
        "Razer",
        "Logitech",
        "Corsair",
        "SteelSeries",
        "HyperX",
        "Western Digital",
        "Seagate",
        "Kingston Technology",
        "G.Skill",
        "Crucial",
        "Broadcom",
        "Marvell",
        "MediaTek",
        "Analog Devices",
        "Texas Instruments",
        "Maxim Integrated",
        
        # HEALTHCARE INNOVATION
        "Teladoc",
        "Veracyte",
        "10x Genomics", 
        "Illumina",
        "Pacific Biosciences",
        "Oxford Nanopore",
        "Moderna",
        "BioNTech",
        "CureVac",
        "Translate Bio",
        "Alnylam",
        "Ionis",
        "Sarepta",
        "Bluebird Bio",
        "CRISPR Therapeutics",
        "Editas Medicine",
        "Intellia Therapeutics",
        
        # FOOD & BEVERAGE
        "Beyond Meat",
        "Impossible Foods",
        "Oatly",
        "Perfect Day",
        "Memphis Meats",
        "Just",
        "Apeel Sciences",
        "Plenty",
        "AeroFarms",
        "Bowery Farming",
        "Gotham Greens",
        "AppHarvest",
        
        # ADDITIONAL CONSULTING & SERVICES
        "Palantir Foundry",
        "Snowflake Inc",
        "Databricks Inc",
        "UiPath",
        "Automation Anywhere",
        "Blue Prism", 
        "WorkFusion",
        "Kryon",
        "NICE",
        "Verint",
        "Genesys",
        "Five9",
        "RingCentral",
        "8x8",
        "Vonage",
        
        # CYBERSECURITY
        "Okta",
        "CyberArk",
        "Fortinet",
        "Check Point",
        "FireEye",
        "Proofpoint",
        "Qualys",
        "Rapid7",
        "Veracode",
        "HackerOne",
        "Bugcrowd", 
        "Synopsys",
        "Checkmarx",
        "Snyk",
        "GitGuardian"
    ]

def main():
    companies = get_master_missing_list()
    
    # Remove duplicates and sort
    unique_companies = sorted(list(set(companies)))
    
    print(f"Total unique missing MBA employer companies: {len(unique_companies)}")
    
    # Save to file
    with open('/Users/adi/code/socratify/socratify-yolo/master_missing_mba_list.txt', 'w') as f:
        f.write("MASTER MISSING MBA EMPLOYER LOGOS\n")
        f.write("=" * 35 + "\n\n")
        f.write(f"Total companies: {len(unique_companies)}\n\n")
        
        for i, company in enumerate(unique_companies, 1):
            f.write(f"{i:3d}. {company}\n")
    
    print("Saved to master_missing_mba_list.txt")
    return unique_companies

if __name__ == "__main__":
    main()